name: hlccalculator
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  fl_chart: ^0.65.0

  share_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Naming.png
    - assets/Background.png
    - assets/Chapters.png
    - assets/Arrow.png
    - assets/Theory.png
    - assets/Test.png
    - assets/Result.png
    - assets/TwitterLogo.png
    - assets/VKLogo.png
    - assets/InstagramLogo.png
    - assets/TelegramLogo.png

  fonts:
    - family: LucGay
      fonts:
        - asset: fonts/LucGay.otf

